- role: Workshop Organizer
  description: "[2nd KAIST-Mila Prefrontal AI Workshop](https://sites.google.com/view/kaist-mila-ai-workshop-2nd) (6 invited speakers incl. [Y. Bengio](https://yoshuabengio.org/))"
- role: Reviewer
  description: "[ICLR 2025](https://iclr.cc/)"